name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm ci
    - name: Run tests with increased logging
      run: |
        echo "Running tests with increased logging..."
        NODE_ENV=test node --experimental-vm-modules node_modules/jest/bin/jest.js --verbose --detectOpenHandles
      env:
        DEBUG: 'app,app:*'  # Adjust this based on your logging setup
    - name: Output server logs if tests fail
      if: failure()
      run: |
        echo "Test failure detected. Outputting server logs..."
        cat server.log  # Adjust the filename as needed
    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          test-results
          coverage
          server.log